runtime: python311

# Optimized scaling within free tier
automatic_scaling:
  min_instances: 1
  max_instances: 3          # Reduced from 10 (more efficient)
  target_cpu_utilization: 0.5  # Scale up sooner (from 0.6)

# Environment variables for the application
env_variables:
  # Flask configuration
  FLASK_ENV: production

# Health check configuration
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# MAXED OUT free tier resources
resources:
  cpu: 1              # 2x faster (was 0.5)
  memory_gb: 1        # 2x more memory (was 0.5)
  disk_size_gb: 10    # 2x more disk (was 5)

# Timeout configuration for webhooks - using single worker to prevent restart issues
entrypoint: gunicorn -b :$PORT whatsapp:app --timeout 120 --workers 1 --worker-class sync --max-requests 1000 